version: "3"

services:
  postgres:
    build: .
    container_name: postgis_pgvector_db
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: peec_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.sh

volumes:
  postgres_data:
